AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    CodeUri: ./src
    Runtime: python3.9
    MemorySize: 512

Outputs:
  TableName:
    Value: !Ref Table

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  PaginationKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy: !Sub |
        {
          "Version": "2012-10-17",
          "Id": "EnableIAM",
          "Statement": [{
            "Sid": "Enable IAM principal policies",
            "Effect": "Allow",
            "Principal": {"AWS": "arn:aws:iam::${AWS::AccountId}:root"},
            "Action": "kms:*",
            "Resource": "*"
          }]
        }

  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: create_function.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - !GetAtt Table.Arn

  ReadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: read_function.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource:
                - !GetAtt Table.Arn

  UpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: update_function.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource:
                - !GetAtt Table.Arn

  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: delete_function.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
              Resource:
                - !GetAtt Table.Arn

  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: list_function.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          PAGINATION_KEY_ARN: !GetAtt PaginationKey.Arn
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
                - dynamodb:Query
              Resource:
                - !GetAtt Table.Arn
            - Effect: Allow
              Action:
                - kms:Encrypt
                - kms:Decrypt
                - kms:GenerateDataKey
              Resource:
                - !GetAtt PaginationKey.Arn
